# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleSignIn'
pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod ‘Alamofire’, ‘~> 5.2’
pod 'Moya', '~> 14.0'
pod 'Moya/RxSwift', '~> 14.0'
pod 'Kingfisher', '~> 5.0'
pod 'SwiftyTimer'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'SPAlert'
pod 'lottie-ios'

  # Pods for ShareUp

end
